In [1]:
import torch
torch.__version__

'2.5.1'

Working on Mac, to test GPU run below

In [3]:
print(torch.backends.mps.is_available())

True


Pytorch tensor datatypes and operations

In [35]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1,2,3])
tensor2d = torch.tensor([[1,2],
                         [3,4]])
tensor3d = torch.tensor([
    [[1,2],
     [3,4]],
    [[5,6],
     [7,8]]])
tensor2by3 = torch.tensor([[1,2,3],
                           [4,5,6]])

print("tensor data type: ", tensor0d.dtype)
print("tensor shape: ",tensor1d.shape)
print("tensor type change from int64 to float32: ",tensor2d.to(torch.float32))
print("tensor viewing: ",tensor2by3.view(2,3))
print("tensor reshaping: ",tensor2by3.reshape(3,2))
print("tensor reshaped: ",tensor2by3.view(3,2))
print("tensor transpose matrix(same as reshape): ",tensor2by3.T)
print(tensor3d.mT)
print("matrix multiplication", tensor2by3.matmul(tensor2by3.T))
print("multiplication can be done also using: ", tensor2by3 @ tensor2by3.T)

tensor data type:  torch.int64
tensor shape:  torch.Size([3])
tensor type change from int64 to float32:  tensor([[1., 2.],
        [3., 4.]])
tensor viewing:  tensor([[1, 2, 3],
        [4, 5, 6]])
tensor reshaping:  tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor reshaped:  tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor transpose matrix(same as reshape):  tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 3],
         [2, 4]],

        [[5, 7],
         [6, 8]]])
matrix multiplication tensor([[14, 32],
        [32, 77]])
multiplication can be done also using:  tensor([[14, 32],
        [32, 77]])


In [37]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)
z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)
grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)
